[package]
name = "pnn-collator-protocol"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
thiserror = "1.0.23"


pdot-primitives = { path = "../../../primitives" }
pnn-protocol = { path = "../../network/protocol" }
pnu-subsystem-util = { path = "../../subsystem-util" }
pnu-validator-discovery = { path = "../../validator-discovery" }
polkadot-subsystem = { package = "pnu-subsystem", path = "../../subsystem" }

[dev-dependencies]
log = "0.4.11"
env_logger = "0.8.2"
assert_matches = "1.4.0"
futures-timer = "3.0.2"

sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", features = ["std"] }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }

polkadot-subsystem-testhelpers = { package = "pnu-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
