[package]
name = "pnc-chain-api"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
polkadot-primitives = { path = "../../../primitives" }
polkadot-subsystem = { package = "pnu-subsystem", path = "../../subsystem" }
pnu-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
futures = { version = "0.3.8", features = ["thread-pool"] }
maplit = "1.0.2"
pnu-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
