name: Push release notes to internal release notes channel
on:
  release:
    types:
      - published
jobs:
  strategy:
    matrix:
      channel:
        # TODO: Test channels, remove before merging
        - '!BtOFjyjPaOPcxxIzll:matrix.parity.io'
        - '!wvmkoSfnHAQEOZKJcg:matrix.parity.io'
#         - '!LhjZccBOqFNYKLdmbb:polkadot.builders' # #KusamaValidatorLounge:polkadot.builders
#         - '!FMwxpQnYhRCNDRsYGI:matrix.parity.io' # #kusama-announcements:matrix.parity.io
#         - '!NZrbtteFeqYKCUGQtr:matrix.parity.io' # #polkadotvalidatorlounge:web3.foundation
#         - '!UqHPWiCBGZWxrmYBkF:matrix.parity.io' # #polkadot-announcements:matrix.parity.io
  ping_matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ matrix.channel }} # heh
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "***Polkadot ${{github.event.release.tag_name}} has been released!***<br/>${{github.event.release.html_url}}<br/><br/>${{github.event.release.body}}<br/>"
          server: "matrix.parity.io"
